[package]
name = "syms"
version = "0.1.0"
authors = ["Kyle Burge <kyle.burge7196@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
