[package]
name = "syms"
version = "0.1.0"
authors = ["Kyle Burge <kyle.burge7196@gmail.com>"]
edition = "2018"

[[bin]]
name = "syms-bin"
path = "src/main.rs"

[lib]
name = "syms"

[dependencies]
string_cache = "0.8"
enum-display-derive = "0.1"
static_assertions = "0.1"
